# https://github.com/helm/charts/tree/master/stable/prometheus-redis-exporter
fullnameOverride: redis-exporter

replicaCount: 1

image:
  repository: oliver006/redis_exporter
  tag: v1.3.4

service:
  type: ClusterIP
  port: 80
  annotations: {}

resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 30m
    memory: 50Mi
