prometheus:
  prometheusSpec:
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 300m
        memory: 300Mi
    externalLabels:
      cluster: kind-kind-multinodes
      region: southamerica-east1-a
